services:
  database:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docer
      POSTGRES_DB: exampledb

    volumes:
      - db-crypto-viz-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-crypto-viz-data:
